#!/usr/bin/env python3
"""Evidence ledger check + report (blueprint sections 47 and 63).

Fails (exit 1) if any page spec cites an evidence ID that data/evidence.json does not define,
so an unsupported claim cannot be published silently. Writes docs/seo-blueprint/04-evidence-ledger.md
with, for every record, the pages that rely on it.

Usage: python3 scripts/seo/build_evidence.py
"""
import glob
import json
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ev = json.load(open(os.path.join(ROOT, "data/evidence.json")))
records = {r["id"]: r for r in ev["records"]}

used = defaultdict(list)
for f in sorted(glob.glob(os.path.join(ROOT, "content/pages/**/*.json"), recursive=True)):
    spec = json.load(open(f))
    for eid in spec.get("evidenceIds", []):
        used[eid].append(spec["url"])

missing = sorted(set(used) - set(records))
unused = sorted(set(records) - set(used))

def cell(s):
    return str(s).replace("|", "/").replace("\n", " ")

L = ["# Evidence ledger", "",
     "> Blueprint sections 47 and 63. Source of truth: `data/evidence.json` (not served). Generated by "
     "`scripts/seo/build_evidence.py`, which fails the build if a page cites an ID that is not recorded here.", "",
     "**How to read `verifiedBy`.** \"site source\" means the claim was checked against what Designit had already "
     "published or what the owner stated in chat. Nobody has checked it against client files yet. "
     "`clientApproved: unknown` means the owner still needs to confirm that client work can be shown.", "",
     f"- Records: {len(records)} · cited by pages: {len(used)} · defined but not cited by a spec: {len(unused)}"
     f" · cited but missing: {len(missing)}", ""]
needs = [r for r in ev["records"] if any(w in r["status"] for w in ("UNVERIFIED", "CONFLICT", "PARTIAL", "NEEDS"))]
L += ["## Needs an owner decision", "", "| ID | Status | Claim | Notes |", "|---|---|---|---|"]
L += [f"| {r['id']} | {r['status']} | {cell(r['claim'])} | {cell(r['notes'])} |" for r in needs]
L += ["", "## All records", "",
      "| ID | Claim | Source | Type | Verified | By | Client approved | Recheck | Pages |", "|---|---|---|---|---|---|---|---|---|"]
for r in ev["records"]:
    pages = ", ".join(f"`{u}`" for u in used.get(r["id"], [])) or "(homepage copy / site-wide)"
    L.append(f"| {r['id']} | {cell(r['claim'])} | {cell(r['source'])} | {r['sourceType']} | {r['dateVerified']} | "
             f"{cell(r['verifiedBy'])} | {cell(r['clientApproved'])} | {r['recheck']} | {pages} |")
L += ["", "## Published claims with no evidence (owner decision required)", "",
      "These are live on the site today. None of them were added by the rebuild; they are listed so they are not forgotten.", "",
      "| ID | Page | Claim | Decision needed |", "|---|---|---|---|"]
L += [f"| {u['id']} | `{u['page']}` | {cell(u['claim'])} | {cell(u['decision'])} |" for u in ev["unverifiedPublished"]["records"]]
L += ["", "## Rules", "",
      "1. Every factual claim on a commercial page, case study or article cites an ID here (spec field `evidenceIds`).",
      "2. A claim without a record is removed or rewritten as a non-factual statement. No invented metrics, clients, reviews, awards, prices or quotes.",
      "3. Client work needs `clientApproved: yes` before new detail is published. Existing published work is grandfathered pending the owner's confirmation.",
      "4. Recheck on the `recheck` date, or when the source changes. Testimonials need their LinkedIn URLs recorded so they are reproducible.", ""]
open(os.path.join(ROOT, "docs/seo-blueprint/04-evidence-ledger.md"), "w").write("\n".join(L))

print(f"{len(records)} records, {len(used)} cited, missing: {missing or 'none'}")
if missing:
    sys.exit(1)
